/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../app/store/store.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/http/src/http_module';
import * as import8 from '../../../app/model/model.module';
import * as import9 from '@angular/router/src/router_module';
import * as import10 from '@angular/common/src/localization';
import * as import11 from '@angular/core/src/application_init';
import * as import12 from '@angular/core/src/testability/testability';
import * as import13 from '@angular/core/src/application_ref';
import * as import14 from '@angular/core/src/linker/compiler';
import * as import15 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import16 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import17 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import18 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import19 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import20 from '@angular/core/src/animation/animation_queue';
import * as import21 from '@angular/core/src/linker/view_utils';
import * as import22 from '@angular/platform-browser/src/browser/title';
import * as import23 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import24 from '@angular/http/src/backends/browser_xhr';
import * as import25 from '@angular/http/src/base_response_options';
import * as import26 from '@angular/http/src/backends/xhr_backend';
import * as import27 from '@angular/http/src/base_request_options';
import * as import28 from '../../../app/model/rest.datasource';
import * as import29 from '../../../app/model/product.repository';
import * as import30 from '../../../app/model/static.datasource';
import * as import31 from '../../../app/model/cart.model';
import * as import32 from '../../../app/model/order.model';
import * as import33 from '../../../app/model/order.repository';
import * as import34 from '../../../app/model/auth.service';
import * as import35 from '@angular/core/src/di/injector';
import * as import36 from '@angular/core/src/i18n/tokens';
import * as import37 from '@angular/core/src/application_tokens';
import * as import38 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import39 from '@angular/platform-browser/src/dom/events/key_events';
import * as import40 from '@angular/core/src/zone/ng_zone';
import * as import41 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import42 from '@angular/core/src/console';
import * as import43 from '@angular/core/src/error_handler';
import * as import44 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import45 from '@angular/platform-browser/src/dom/animation_driver';
import * as import46 from '@angular/core/src/render/api';
import * as import47 from '@angular/core/src/security';
import * as import48 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import49 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import50 from '@angular/http/src/interfaces';
import * as import51 from '@angular/http/src/http';
class StoreModuleInjector extends import0.NgModuleInjector<import1.StoreModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _HttpModule_5:import7.HttpModule;
  _ModelModule_6:import8.ModelModule;
  _RouterModule_7:import9.RouterModule;
  _StoreModule_8:import1.StoreModule;
  __LOCALE_ID_9:any;
  __NgLocalization_10:import10.NgLocaleLocalization;
  _ErrorHandler_11:any;
  _ApplicationInitStatus_12:import11.ApplicationInitStatus;
  _Testability_13:import12.Testability;
  _ApplicationRef__14:import13.ApplicationRef_;
  __ApplicationRef_15:any;
  __Compiler_16:import14.Compiler;
  __APP_ID_17:any;
  __DOCUMENT_18:any;
  __HAMMER_GESTURE_CONFIG_19:import15.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_20:any[];
  __EventManager_21:import16.EventManager;
  _DomSharedStylesHost_22:import17.DomSharedStylesHost;
  __AnimationDriver_23:any;
  __DomRootRenderer_24:import18.DomRootRenderer_;
  __RootRenderer_25:any;
  __DomSanitizer_26:import19.DomSanitizerImpl;
  __Sanitizer_27:any;
  __AnimationQueue_28:import20.AnimationQueue;
  __ViewUtils_29:import21.ViewUtils;
  __IterableDiffers_30:any;
  __KeyValueDiffers_31:any;
  __SharedStylesHost_32:any;
  __Title_33:import22.Title;
  __RadioControlRegistry_34:import23.RadioControlRegistry;
  __BrowserXhr_35:import24.BrowserXhr;
  __ResponseOptions_36:import25.BaseResponseOptions;
  __XSRFStrategy_37:any;
  __XHRBackend_38:import26.XHRBackend;
  __RequestOptions_39:import27.BaseRequestOptions;
  __Http_40:any;
  __RestDataSource_41:import28.RestDataSource;
  __ProductRepository_42:import29.ProductRepository;
  __StaticDataSource_43:import30.StaticDataSource;
  __Cart_44:import31.Cart;
  __Order_45:import32.Order;
  __OrderRepository_46:import33.OrderRepository;
  __AuthService_47:import34.AuthService;
  constructor(parent:import35.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _LOCALE_ID_9():any {
    if ((this.__LOCALE_ID_9 == null)) { (this.__LOCALE_ID_9 = import3._localeFactory(this.parent.get(import36.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_9;
  }
  get _NgLocalization_10():import10.NgLocaleLocalization {
    if ((this.__NgLocalization_10 == null)) { (this.__NgLocalization_10 = new import10.NgLocaleLocalization(this._LOCALE_ID_9)); }
    return this.__NgLocalization_10;
  }
  get _ApplicationRef_15():any {
    if ((this.__ApplicationRef_15 == null)) { (this.__ApplicationRef_15 = this._ApplicationRef__14); }
    return this.__ApplicationRef_15;
  }
  get _Compiler_16():import14.Compiler {
    if ((this.__Compiler_16 == null)) { (this.__Compiler_16 = new import14.Compiler()); }
    return this.__Compiler_16;
  }
  get _APP_ID_17():any {
    if ((this.__APP_ID_17 == null)) { (this.__APP_ID_17 = import37._appIdRandomProviderFactory()); }
    return this.__APP_ID_17;
  }
  get _DOCUMENT_18():any {
    if ((this.__DOCUMENT_18 == null)) { (this.__DOCUMENT_18 = import4._document()); }
    return this.__DOCUMENT_18;
  }
  get _HAMMER_GESTURE_CONFIG_19():import15.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_19 == null)) { (this.__HAMMER_GESTURE_CONFIG_19 = new import15.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_19;
  }
  get _EVENT_MANAGER_PLUGINS_20():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_20 == null)) { (this.__EVENT_MANAGER_PLUGINS_20 = [
      new import38.DomEventsPlugin(),
      new import39.KeyEventsPlugin(),
      new import15.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_19)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_20;
  }
  get _EventManager_21():import16.EventManager {
    if ((this.__EventManager_21 == null)) { (this.__EventManager_21 = new import16.EventManager(this._EVENT_MANAGER_PLUGINS_20,this.parent.get(import40.NgZone))); }
    return this.__EventManager_21;
  }
  get _AnimationDriver_23():any {
    if ((this.__AnimationDriver_23 == null)) { (this.__AnimationDriver_23 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_23;
  }
  get _DomRootRenderer_24():import18.DomRootRenderer_ {
    if ((this.__DomRootRenderer_24 == null)) { (this.__DomRootRenderer_24 = new import18.DomRootRenderer_(this._DOCUMENT_18,this._EventManager_21,this._DomSharedStylesHost_22,this._AnimationDriver_23,this._APP_ID_17)); }
    return this.__DomRootRenderer_24;
  }
  get _RootRenderer_25():any {
    if ((this.__RootRenderer_25 == null)) { (this.__RootRenderer_25 = import41._createConditionalRootRenderer(this._DomRootRenderer_24,this.parent.get(import41.NgProbeToken,(null as any)),this.parent.get(import13.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_25;
  }
  get _DomSanitizer_26():import19.DomSanitizerImpl {
    if ((this.__DomSanitizer_26 == null)) { (this.__DomSanitizer_26 = new import19.DomSanitizerImpl()); }
    return this.__DomSanitizer_26;
  }
  get _Sanitizer_27():any {
    if ((this.__Sanitizer_27 == null)) { (this.__Sanitizer_27 = this._DomSanitizer_26); }
    return this.__Sanitizer_27;
  }
  get _AnimationQueue_28():import20.AnimationQueue {
    if ((this.__AnimationQueue_28 == null)) { (this.__AnimationQueue_28 = new import20.AnimationQueue(this.parent.get(import40.NgZone))); }
    return this.__AnimationQueue_28;
  }
  get _ViewUtils_29():import21.ViewUtils {
    if ((this.__ViewUtils_29 == null)) { (this.__ViewUtils_29 = new import21.ViewUtils(this._RootRenderer_25,this._Sanitizer_27,this._AnimationQueue_28)); }
    return this.__ViewUtils_29;
  }
  get _IterableDiffers_30():any {
    if ((this.__IterableDiffers_30 == null)) { (this.__IterableDiffers_30 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_30;
  }
  get _KeyValueDiffers_31():any {
    if ((this.__KeyValueDiffers_31 == null)) { (this.__KeyValueDiffers_31 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_31;
  }
  get _SharedStylesHost_32():any {
    if ((this.__SharedStylesHost_32 == null)) { (this.__SharedStylesHost_32 = this._DomSharedStylesHost_22); }
    return this.__SharedStylesHost_32;
  }
  get _Title_33():import22.Title {
    if ((this.__Title_33 == null)) { (this.__Title_33 = new import22.Title()); }
    return this.__Title_33;
  }
  get _RadioControlRegistry_34():import23.RadioControlRegistry {
    if ((this.__RadioControlRegistry_34 == null)) { (this.__RadioControlRegistry_34 = new import23.RadioControlRegistry()); }
    return this.__RadioControlRegistry_34;
  }
  get _BrowserXhr_35():import24.BrowserXhr {
    if ((this.__BrowserXhr_35 == null)) { (this.__BrowserXhr_35 = new import24.BrowserXhr()); }
    return this.__BrowserXhr_35;
  }
  get _ResponseOptions_36():import25.BaseResponseOptions {
    if ((this.__ResponseOptions_36 == null)) { (this.__ResponseOptions_36 = new import25.BaseResponseOptions()); }
    return this.__ResponseOptions_36;
  }
  get _XSRFStrategy_37():any {
    if ((this.__XSRFStrategy_37 == null)) { (this.__XSRFStrategy_37 = import7._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_37;
  }
  get _XHRBackend_38():import26.XHRBackend {
    if ((this.__XHRBackend_38 == null)) { (this.__XHRBackend_38 = new import26.XHRBackend(this._BrowserXhr_35,this._ResponseOptions_36,this._XSRFStrategy_37)); }
    return this.__XHRBackend_38;
  }
  get _RequestOptions_39():import27.BaseRequestOptions {
    if ((this.__RequestOptions_39 == null)) { (this.__RequestOptions_39 = new import27.BaseRequestOptions()); }
    return this.__RequestOptions_39;
  }
  get _Http_40():any {
    if ((this.__Http_40 == null)) { (this.__Http_40 = import7.httpFactory(this._XHRBackend_38,this._RequestOptions_39)); }
    return this.__Http_40;
  }
  get _RestDataSource_41():import28.RestDataSource {
    if ((this.__RestDataSource_41 == null)) { (this.__RestDataSource_41 = new import28.RestDataSource(this._Http_40)); }
    return this.__RestDataSource_41;
  }
  get _ProductRepository_42():import29.ProductRepository {
    if ((this.__ProductRepository_42 == null)) { (this.__ProductRepository_42 = new import29.ProductRepository(this._RestDataSource_41)); }
    return this.__ProductRepository_42;
  }
  get _StaticDataSource_43():import30.StaticDataSource {
    if ((this.__StaticDataSource_43 == null)) { (this.__StaticDataSource_43 = new import30.StaticDataSource()); }
    return this.__StaticDataSource_43;
  }
  get _Cart_44():import31.Cart {
    if ((this.__Cart_44 == null)) { (this.__Cart_44 = new import31.Cart()); }
    return this.__Cart_44;
  }
  get _Order_45():import32.Order {
    if ((this.__Order_45 == null)) { (this.__Order_45 = new import32.Order(this._Cart_44)); }
    return this.__Order_45;
  }
  get _OrderRepository_46():import33.OrderRepository {
    if ((this.__OrderRepository_46 == null)) { (this.__OrderRepository_46 = new import33.OrderRepository(this._RestDataSource_41)); }
    return this.__OrderRepository_46;
  }
  get _AuthService_47():import34.AuthService {
    if ((this.__AuthService_47 == null)) { (this.__AuthService_47 = new import34.AuthService(this._RestDataSource_41)); }
    return this.__AuthService_47;
  }
  createInternal():import1.StoreModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._HttpModule_5 = new import7.HttpModule();
    this._ModelModule_6 = new import8.ModelModule();
    this._RouterModule_7 = new import9.RouterModule(this.parent.get(import9.ROUTER_FORROOT_GUARD,(null as any)));
    this._StoreModule_8 = new import1.StoreModule();
    this._ErrorHandler_11 = import4.errorHandler();
    this._ApplicationInitStatus_12 = new import11.ApplicationInitStatus(this.parent.get(import11.APP_INITIALIZER,(null as any)));
    this._Testability_13 = new import12.Testability(this.parent.get(import40.NgZone));
    this._ApplicationRef__14 = new import13.ApplicationRef_(this.parent.get(import40.NgZone),this.parent.get(import42.Console),this,this._ErrorHandler_11,this,this._ApplicationInitStatus_12,this.parent.get(import12.TestabilityRegistry,(null as any)),this._Testability_13);
    this._DomSharedStylesHost_22 = new import17.DomSharedStylesHost(this._DOCUMENT_18);
    return this._StoreModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.HttpModule)) { return this._HttpModule_5; }
    if ((token === import8.ModelModule)) { return this._ModelModule_6; }
    if ((token === import9.RouterModule)) { return this._RouterModule_7; }
    if ((token === import1.StoreModule)) { return this._StoreModule_8; }
    if ((token === import36.LOCALE_ID)) { return this._LOCALE_ID_9; }
    if ((token === import10.NgLocalization)) { return this._NgLocalization_10; }
    if ((token === import43.ErrorHandler)) { return this._ErrorHandler_11; }
    if ((token === import11.ApplicationInitStatus)) { return this._ApplicationInitStatus_12; }
    if ((token === import12.Testability)) { return this._Testability_13; }
    if ((token === import13.ApplicationRef_)) { return this._ApplicationRef__14; }
    if ((token === import13.ApplicationRef)) { return this._ApplicationRef_15; }
    if ((token === import14.Compiler)) { return this._Compiler_16; }
    if ((token === import37.APP_ID)) { return this._APP_ID_17; }
    if ((token === import44.DOCUMENT)) { return this._DOCUMENT_18; }
    if ((token === import15.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_19; }
    if ((token === import16.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_20; }
    if ((token === import16.EventManager)) { return this._EventManager_21; }
    if ((token === import17.DomSharedStylesHost)) { return this._DomSharedStylesHost_22; }
    if ((token === import45.AnimationDriver)) { return this._AnimationDriver_23; }
    if ((token === import18.DomRootRenderer)) { return this._DomRootRenderer_24; }
    if ((token === import46.RootRenderer)) { return this._RootRenderer_25; }
    if ((token === import19.DomSanitizer)) { return this._DomSanitizer_26; }
    if ((token === import47.Sanitizer)) { return this._Sanitizer_27; }
    if ((token === import20.AnimationQueue)) { return this._AnimationQueue_28; }
    if ((token === import21.ViewUtils)) { return this._ViewUtils_29; }
    if ((token === import48.IterableDiffers)) { return this._IterableDiffers_30; }
    if ((token === import49.KeyValueDiffers)) { return this._KeyValueDiffers_31; }
    if ((token === import17.SharedStylesHost)) { return this._SharedStylesHost_32; }
    if ((token === import22.Title)) { return this._Title_33; }
    if ((token === import23.RadioControlRegistry)) { return this._RadioControlRegistry_34; }
    if ((token === import24.BrowserXhr)) { return this._BrowserXhr_35; }
    if ((token === import25.ResponseOptions)) { return this._ResponseOptions_36; }
    if ((token === import50.XSRFStrategy)) { return this._XSRFStrategy_37; }
    if ((token === import26.XHRBackend)) { return this._XHRBackend_38; }
    if ((token === import27.RequestOptions)) { return this._RequestOptions_39; }
    if ((token === import51.Http)) { return this._Http_40; }
    if ((token === import28.RestDataSource)) { return this._RestDataSource_41; }
    if ((token === import29.ProductRepository)) { return this._ProductRepository_42; }
    if ((token === import30.StaticDataSource)) { return this._StaticDataSource_43; }
    if ((token === import31.Cart)) { return this._Cart_44; }
    if ((token === import32.Order)) { return this._Order_45; }
    if ((token === import33.OrderRepository)) { return this._OrderRepository_46; }
    if ((token === import34.AuthService)) { return this._AuthService_47; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__14.ngOnDestroy();
    this._DomSharedStylesHost_22.ngOnDestroy();
  }
}
export const StoreModuleNgFactory:import0.NgModuleFactory<import1.StoreModule> = new import0.NgModuleFactory(StoreModuleInjector,import1.StoreModule);