/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/http/src/http_module';
import * as import8 from '../../app/model/model.module';
import * as import9 from '@angular/router/src/router_module';
import * as import10 from '../../app/store/store.module';
import * as import11 from '@angular/common/src/localization';
import * as import12 from '@angular/core/src/application_init';
import * as import13 from '@angular/core/src/testability/testability';
import * as import14 from '@angular/core/src/application_ref';
import * as import15 from '@angular/core/src/linker/compiler';
import * as import16 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import17 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import18 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import19 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import20 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import21 from '@angular/core/src/animation/animation_queue';
import * as import22 from '@angular/core/src/linker/view_utils';
import * as import23 from '@angular/platform-browser/src/browser/title';
import * as import24 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import25 from '@angular/http/src/backends/browser_xhr';
import * as import26 from '@angular/http/src/base_response_options';
import * as import27 from '@angular/http/src/backends/xhr_backend';
import * as import28 from '@angular/http/src/base_request_options';
import * as import29 from '../../app/model/rest.datasource';
import * as import30 from '../../app/model/product.repository';
import * as import31 from '../../app/model/static.datasource';
import * as import32 from '../../app/model/cart.model';
import * as import33 from '../../app/model/order.model';
import * as import34 from '../../app/model/order.repository';
import * as import35 from '../../app/model/auth.service';
import * as import36 from '@angular/common/src/location/location';
import * as import37 from '@angular/router/src/url_tree';
import * as import38 from '@angular/router/src/router_outlet_map';
import * as import39 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import40 from '@angular/router/src/router_preloader';
import * as import41 from '../../app/storeFirst.gaurd';
import * as import42 from '@angular/core/src/di/injector';
import * as import43 from './store/store.component.ngfactory';
import * as import44 from './store/cartDetail.component.ngfactory';
import * as import45 from './store/checkout.component.ngfactory';
import * as import46 from './admin/auth.component.ngfactory';
import * as import47 from './admin/admin.component.ngfactory';
import * as import48 from './admin/productEditor.component.ngfactory';
import * as import49 from './admin/productTable.component.ngfactory';
import * as import50 from './admin/orderTable.component.ngfactory';
import * as import51 from './app.component.ngfactory';
import * as import52 from '@angular/core/src/i18n/tokens';
import * as import53 from '@angular/core/src/application_tokens';
import * as import54 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import55 from '@angular/platform-browser/src/dom/events/key_events';
import * as import56 from '@angular/core/src/zone/ng_zone';
import * as import57 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import58 from '@angular/common/src/location/platform_location';
import * as import59 from '@angular/common/src/location/location_strategy';
import * as import60 from '../../app/store/store.component';
import * as import61 from '../../app/store/cartDetail.component';
import * as import62 from '../../app/store/checkout.component';
import * as import63 from '../../app/admin/auth.component';
import * as import64 from '../../app/admin/admin.component';
import * as import65 from '../../app/admin/auth.guard';
import * as import66 from '../../app/admin/productEditor.component';
import * as import67 from '../../app/admin/productTable.component';
import * as import68 from '../../app/admin/orderTable.component';
import * as import69 from '@angular/router/src/url_handling_strategy';
import * as import70 from '@angular/router/src/route_reuse_strategy';
import * as import71 from '@angular/router/src/router';
import * as import72 from '@angular/core/src/console';
import * as import73 from '@angular/core/src/error_handler';
import * as import74 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import75 from '@angular/platform-browser/src/dom/animation_driver';
import * as import76 from '@angular/core/src/render/api';
import * as import77 from '@angular/core/src/security';
import * as import78 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import79 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import80 from '@angular/http/src/interfaces';
import * as import81 from '@angular/http/src/http';
import * as import82 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import83 from '@angular/router/src/router_config_loader';
import * as import84 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _HttpModule_5:import7.HttpModule;
  _ModelModule_6:import8.ModelModule;
  _ROUTER_FORROOT_GUARD_7:any;
  _RouterModule_8:import9.RouterModule;
  _StoreModule_9:import10.StoreModule;
  _AppModule_10:import1.AppModule;
  __LOCALE_ID_11:any;
  __NgLocalization_12:import11.NgLocaleLocalization;
  _ErrorHandler_13:any;
  _ApplicationInitStatus_14:import12.ApplicationInitStatus;
  _Testability_15:import13.Testability;
  _ApplicationRef__16:import14.ApplicationRef_;
  __ApplicationRef_17:any;
  __Compiler_18:import15.Compiler;
  __APP_ID_19:any;
  __DOCUMENT_20:any;
  __HAMMER_GESTURE_CONFIG_21:import16.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_22:any[];
  __EventManager_23:import17.EventManager;
  _DomSharedStylesHost_24:import18.DomSharedStylesHost;
  __AnimationDriver_25:any;
  __DomRootRenderer_26:import19.DomRootRenderer_;
  __NgProbeToken_27:any[];
  __RootRenderer_28:any;
  __DomSanitizer_29:import20.DomSanitizerImpl;
  __Sanitizer_30:any;
  __AnimationQueue_31:import21.AnimationQueue;
  __ViewUtils_32:import22.ViewUtils;
  __IterableDiffers_33:any;
  __KeyValueDiffers_34:any;
  __SharedStylesHost_35:any;
  __Title_36:import23.Title;
  __RadioControlRegistry_37:import24.RadioControlRegistry;
  __BrowserXhr_38:import25.BrowserXhr;
  __ResponseOptions_39:import26.BaseResponseOptions;
  __XSRFStrategy_40:any;
  __XHRBackend_41:import27.XHRBackend;
  __RequestOptions_42:import28.BaseRequestOptions;
  __Http_43:any;
  __RestDataSource_44:import29.RestDataSource;
  __ProductRepository_45:import30.ProductRepository;
  __StaticDataSource_46:import31.StaticDataSource;
  __Cart_47:import32.Cart;
  __Order_48:import33.Order;
  __OrderRepository_49:import34.OrderRepository;
  __AuthService_50:import35.AuthService;
  __ROUTER_CONFIGURATION_51:any;
  __LocationStrategy_52:any;
  __Location_53:import36.Location;
  __UrlSerializer_54:import37.DefaultUrlSerializer;
  __RouterOutletMap_55:import38.RouterOutletMap;
  __NgModuleFactoryLoader_56:import39.SystemJsNgModuleLoader;
  __ROUTES_57:any[];
  __Router_58:any;
  __ActivatedRoute_59:any;
  _NoPreloading_60:import40.NoPreloading;
  _PreloadingStrategy_61:any;
  _RouterPreloader_62:import40.RouterPreloader;
  __PreloadAllModules_63:import40.PreloadAllModules;
  __ROUTER_INITIALIZER_64:any;
  __APP_BOOTSTRAP_LISTENER_65:any[];
  __StoreFirstGuard_66:import41.StoreFirstGuard;
  constructor(parent:import42.Injector) {
    super(parent,[
      import43.StoreComponentNgFactory,
      import44.CartDetailComponentNgFactory,
      import45.CheckoutComponentNgFactory,
      import46.AuthComponentNgFactory,
      import47.AdminComponentNgFactory,
      import48.ProductEditorComponentNgFactory,
      import49.ProductTableComponentNgFactory,
      import50.OrderTableComponentNgFactory,
      import51.AppComponentNgFactory
    ]
    ,[import51.AppComponentNgFactory]);
  }
  get _LOCALE_ID_11():any {
    if ((this.__LOCALE_ID_11 == null)) { (this.__LOCALE_ID_11 = import3._localeFactory(this.parent.get(import52.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_11;
  }
  get _NgLocalization_12():import11.NgLocaleLocalization {
    if ((this.__NgLocalization_12 == null)) { (this.__NgLocalization_12 = new import11.NgLocaleLocalization(this._LOCALE_ID_11)); }
    return this.__NgLocalization_12;
  }
  get _ApplicationRef_17():any {
    if ((this.__ApplicationRef_17 == null)) { (this.__ApplicationRef_17 = this._ApplicationRef__16); }
    return this.__ApplicationRef_17;
  }
  get _Compiler_18():import15.Compiler {
    if ((this.__Compiler_18 == null)) { (this.__Compiler_18 = new import15.Compiler()); }
    return this.__Compiler_18;
  }
  get _APP_ID_19():any {
    if ((this.__APP_ID_19 == null)) { (this.__APP_ID_19 = import53._appIdRandomProviderFactory()); }
    return this.__APP_ID_19;
  }
  get _DOCUMENT_20():any {
    if ((this.__DOCUMENT_20 == null)) { (this.__DOCUMENT_20 = import4._document()); }
    return this.__DOCUMENT_20;
  }
  get _HAMMER_GESTURE_CONFIG_21():import16.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_21 == null)) { (this.__HAMMER_GESTURE_CONFIG_21 = new import16.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_21;
  }
  get _EVENT_MANAGER_PLUGINS_22():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_22 == null)) { (this.__EVENT_MANAGER_PLUGINS_22 = [
      new import54.DomEventsPlugin(),
      new import55.KeyEventsPlugin(),
      new import16.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_21)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_22;
  }
  get _EventManager_23():import17.EventManager {
    if ((this.__EventManager_23 == null)) { (this.__EventManager_23 = new import17.EventManager(this._EVENT_MANAGER_PLUGINS_22,this.parent.get(import56.NgZone))); }
    return this.__EventManager_23;
  }
  get _AnimationDriver_25():any {
    if ((this.__AnimationDriver_25 == null)) { (this.__AnimationDriver_25 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_25;
  }
  get _DomRootRenderer_26():import19.DomRootRenderer_ {
    if ((this.__DomRootRenderer_26 == null)) { (this.__DomRootRenderer_26 = new import19.DomRootRenderer_(this._DOCUMENT_20,this._EventManager_23,this._DomSharedStylesHost_24,this._AnimationDriver_25,this._APP_ID_19)); }
    return this.__DomRootRenderer_26;
  }
  get _NgProbeToken_27():any[] {
    if ((this.__NgProbeToken_27 == null)) { (this.__NgProbeToken_27 = [import9.routerNgProbeToken()]); }
    return this.__NgProbeToken_27;
  }
  get _RootRenderer_28():any {
    if ((this.__RootRenderer_28 == null)) { (this.__RootRenderer_28 = import57._createConditionalRootRenderer(this._DomRootRenderer_26,this.parent.get(import57.NgProbeToken,(null as any)),this._NgProbeToken_27)); }
    return this.__RootRenderer_28;
  }
  get _DomSanitizer_29():import20.DomSanitizerImpl {
    if ((this.__DomSanitizer_29 == null)) { (this.__DomSanitizer_29 = new import20.DomSanitizerImpl()); }
    return this.__DomSanitizer_29;
  }
  get _Sanitizer_30():any {
    if ((this.__Sanitizer_30 == null)) { (this.__Sanitizer_30 = this._DomSanitizer_29); }
    return this.__Sanitizer_30;
  }
  get _AnimationQueue_31():import21.AnimationQueue {
    if ((this.__AnimationQueue_31 == null)) { (this.__AnimationQueue_31 = new import21.AnimationQueue(this.parent.get(import56.NgZone))); }
    return this.__AnimationQueue_31;
  }
  get _ViewUtils_32():import22.ViewUtils {
    if ((this.__ViewUtils_32 == null)) { (this.__ViewUtils_32 = new import22.ViewUtils(this._RootRenderer_28,this._Sanitizer_30,this._AnimationQueue_31)); }
    return this.__ViewUtils_32;
  }
  get _IterableDiffers_33():any {
    if ((this.__IterableDiffers_33 == null)) { (this.__IterableDiffers_33 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_33;
  }
  get _KeyValueDiffers_34():any {
    if ((this.__KeyValueDiffers_34 == null)) { (this.__KeyValueDiffers_34 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_34;
  }
  get _SharedStylesHost_35():any {
    if ((this.__SharedStylesHost_35 == null)) { (this.__SharedStylesHost_35 = this._DomSharedStylesHost_24); }
    return this.__SharedStylesHost_35;
  }
  get _Title_36():import23.Title {
    if ((this.__Title_36 == null)) { (this.__Title_36 = new import23.Title()); }
    return this.__Title_36;
  }
  get _RadioControlRegistry_37():import24.RadioControlRegistry {
    if ((this.__RadioControlRegistry_37 == null)) { (this.__RadioControlRegistry_37 = new import24.RadioControlRegistry()); }
    return this.__RadioControlRegistry_37;
  }
  get _BrowserXhr_38():import25.BrowserXhr {
    if ((this.__BrowserXhr_38 == null)) { (this.__BrowserXhr_38 = new import25.BrowserXhr()); }
    return this.__BrowserXhr_38;
  }
  get _ResponseOptions_39():import26.BaseResponseOptions {
    if ((this.__ResponseOptions_39 == null)) { (this.__ResponseOptions_39 = new import26.BaseResponseOptions()); }
    return this.__ResponseOptions_39;
  }
  get _XSRFStrategy_40():any {
    if ((this.__XSRFStrategy_40 == null)) { (this.__XSRFStrategy_40 = import7._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_40;
  }
  get _XHRBackend_41():import27.XHRBackend {
    if ((this.__XHRBackend_41 == null)) { (this.__XHRBackend_41 = new import27.XHRBackend(this._BrowserXhr_38,this._ResponseOptions_39,this._XSRFStrategy_40)); }
    return this.__XHRBackend_41;
  }
  get _RequestOptions_42():import28.BaseRequestOptions {
    if ((this.__RequestOptions_42 == null)) { (this.__RequestOptions_42 = new import28.BaseRequestOptions()); }
    return this.__RequestOptions_42;
  }
  get _Http_43():any {
    if ((this.__Http_43 == null)) { (this.__Http_43 = import7.httpFactory(this._XHRBackend_41,this._RequestOptions_42)); }
    return this.__Http_43;
  }
  get _RestDataSource_44():import29.RestDataSource {
    if ((this.__RestDataSource_44 == null)) { (this.__RestDataSource_44 = new import29.RestDataSource(this._Http_43)); }
    return this.__RestDataSource_44;
  }
  get _ProductRepository_45():import30.ProductRepository {
    if ((this.__ProductRepository_45 == null)) { (this.__ProductRepository_45 = new import30.ProductRepository(this._RestDataSource_44)); }
    return this.__ProductRepository_45;
  }
  get _StaticDataSource_46():import31.StaticDataSource {
    if ((this.__StaticDataSource_46 == null)) { (this.__StaticDataSource_46 = new import31.StaticDataSource()); }
    return this.__StaticDataSource_46;
  }
  get _Cart_47():import32.Cart {
    if ((this.__Cart_47 == null)) { (this.__Cart_47 = new import32.Cart()); }
    return this.__Cart_47;
  }
  get _Order_48():import33.Order {
    if ((this.__Order_48 == null)) { (this.__Order_48 = new import33.Order(this._Cart_47)); }
    return this.__Order_48;
  }
  get _OrderRepository_49():import34.OrderRepository {
    if ((this.__OrderRepository_49 == null)) { (this.__OrderRepository_49 = new import34.OrderRepository(this._RestDataSource_44)); }
    return this.__OrderRepository_49;
  }
  get _AuthService_50():import35.AuthService {
    if ((this.__AuthService_50 == null)) { (this.__AuthService_50 = new import35.AuthService(this._RestDataSource_44)); }
    return this.__AuthService_50;
  }
  get _ROUTER_CONFIGURATION_51():any {
    if ((this.__ROUTER_CONFIGURATION_51 == null)) { (this.__ROUTER_CONFIGURATION_51 = {}); }
    return this.__ROUTER_CONFIGURATION_51;
  }
  get _LocationStrategy_52():any {
    if ((this.__LocationStrategy_52 == null)) { (this.__LocationStrategy_52 = import9.provideLocationStrategy(this.parent.get(import58.PlatformLocation),this.parent.get(import59.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_51)); }
    return this.__LocationStrategy_52;
  }
  get _Location_53():import36.Location {
    if ((this.__Location_53 == null)) { (this.__Location_53 = new import36.Location(this._LocationStrategy_52)); }
    return this.__Location_53;
  }
  get _UrlSerializer_54():import37.DefaultUrlSerializer {
    if ((this.__UrlSerializer_54 == null)) { (this.__UrlSerializer_54 = new import37.DefaultUrlSerializer()); }
    return this.__UrlSerializer_54;
  }
  get _RouterOutletMap_55():import38.RouterOutletMap {
    if ((this.__RouterOutletMap_55 == null)) { (this.__RouterOutletMap_55 = new import38.RouterOutletMap()); }
    return this.__RouterOutletMap_55;
  }
  get _NgModuleFactoryLoader_56():import39.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_56 == null)) { (this.__NgModuleFactoryLoader_56 = new import39.SystemJsNgModuleLoader(this._Compiler_18,this.parent.get(import39.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_56;
  }
  get _ROUTES_57():any[] {
      if ((this.__ROUTES_57 == null)) { (this.__ROUTES_57 = [[
        {
          path: 'store',
          component: import60.StoreComponent,
          canActivate: [import41.StoreFirstGuard]
        }
        ,
        {
          path: 'cart',
          component: import61.CartDetailComponent,
          canActivate: [import41.StoreFirstGuard]
        }
        ,
        {
          path: 'checkout',
          component: import62.CheckoutComponent,
          canActivate: [import41.StoreFirstGuard]
        }
        ,
        {
          path: 'admin',
          children: [
            {
              path: 'auth',
              component: import63.AuthComponent
            }
            ,
            {
              path: 'main',
              component: import64.AdminComponent,
              canActivate: [import65.AuthGuard],
              children: [
                {
                  path: 'products/:mode/:id',
                  component: import66.ProductEditorComponent
                }
                ,
                {
                  path: 'products/:mode',
                  component: import66.ProductEditorComponent
                }
                ,
                {
                  path: 'products',
                  component: import67.ProductTableComponent
                }
                ,
                {
                  path: 'orders',
                  component: import68.OrderTableComponent
                }
                ,
                {
                  path: '**',
                  redirectTo: 'products'
                }

              ]

            }
            ,
            {
              path: '**',
              redirectTo: 'auth'
            }

          ]
          ,
          canActivate: [import41.StoreFirstGuard]
        }
        ,
        {
          path: '**',
          redirectTo: '/store'
        }

      ]
    ]); }
    return this.__ROUTES_57;
  }
  get _Router_58():any {
    if ((this.__Router_58 == null)) { (this.__Router_58 = import9.setupRouter(this._ApplicationRef_17,this._UrlSerializer_54,this._RouterOutletMap_55,this._Location_53,this,this._NgModuleFactoryLoader_56,this._Compiler_18,this._ROUTES_57,this._ROUTER_CONFIGURATION_51,this.parent.get(import69.UrlHandlingStrategy,(null as any)),this.parent.get(import70.RouteReuseStrategy,(null as any)))); }
    return this.__Router_58;
  }
  get _ActivatedRoute_59():any {
    if ((this.__ActivatedRoute_59 == null)) { (this.__ActivatedRoute_59 = import9.rootRoute(this._Router_58)); }
    return this.__ActivatedRoute_59;
  }
  get _PreloadAllModules_63():import40.PreloadAllModules {
    if ((this.__PreloadAllModules_63 == null)) { (this.__PreloadAllModules_63 = new import40.PreloadAllModules()); }
    return this.__PreloadAllModules_63;
  }
  get _ROUTER_INITIALIZER_64():any {
    if ((this.__ROUTER_INITIALIZER_64 == null)) { (this.__ROUTER_INITIALIZER_64 = import9.initialRouterNavigation(this._Router_58,this._ApplicationRef_17,this._RouterPreloader_62,this._ROUTER_CONFIGURATION_51)); }
    return this.__ROUTER_INITIALIZER_64;
  }
  get _APP_BOOTSTRAP_LISTENER_65():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_65 == null)) { (this.__APP_BOOTSTRAP_LISTENER_65 = [this._ROUTER_INITIALIZER_64]); }
    return this.__APP_BOOTSTRAP_LISTENER_65;
  }
  get _StoreFirstGuard_66():import41.StoreFirstGuard {
    if ((this.__StoreFirstGuard_66 == null)) { (this.__StoreFirstGuard_66 = new import41.StoreFirstGuard(this._Router_58)); }
    return this.__StoreFirstGuard_66;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._HttpModule_5 = new import7.HttpModule();
    this._ModelModule_6 = new import8.ModelModule();
    this._ROUTER_FORROOT_GUARD_7 = import9.provideForRootGuard(this.parent.get(import71.Router,(null as any)));
    this._RouterModule_8 = new import9.RouterModule(this._ROUTER_FORROOT_GUARD_7);
    this._StoreModule_9 = new import10.StoreModule();
    this._AppModule_10 = new import1.AppModule();
    this._ErrorHandler_13 = import4.errorHandler();
    this._ApplicationInitStatus_14 = new import12.ApplicationInitStatus(this.parent.get(import12.APP_INITIALIZER,(null as any)));
    this._Testability_15 = new import13.Testability(this.parent.get(import56.NgZone));
    this._ApplicationRef__16 = new import14.ApplicationRef_(this.parent.get(import56.NgZone),this.parent.get(import72.Console),this,this._ErrorHandler_13,this,this._ApplicationInitStatus_14,this.parent.get(import13.TestabilityRegistry,(null as any)),this._Testability_15);
    this._DomSharedStylesHost_24 = new import18.DomSharedStylesHost(this._DOCUMENT_20);
    this._NoPreloading_60 = new import40.NoPreloading();
    this._PreloadingStrategy_61 = this._NoPreloading_60;
    this._RouterPreloader_62 = new import40.RouterPreloader(this._Router_58,this._NgModuleFactoryLoader_56,this._Compiler_18,this,this._PreloadingStrategy_61);
    return this._AppModule_10;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.HttpModule)) { return this._HttpModule_5; }
    if ((token === import8.ModelModule)) { return this._ModelModule_6; }
    if ((token === import9.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_7; }
    if ((token === import9.RouterModule)) { return this._RouterModule_8; }
    if ((token === import10.StoreModule)) { return this._StoreModule_9; }
    if ((token === import1.AppModule)) { return this._AppModule_10; }
    if ((token === import52.LOCALE_ID)) { return this._LOCALE_ID_11; }
    if ((token === import11.NgLocalization)) { return this._NgLocalization_12; }
    if ((token === import73.ErrorHandler)) { return this._ErrorHandler_13; }
    if ((token === import12.ApplicationInitStatus)) { return this._ApplicationInitStatus_14; }
    if ((token === import13.Testability)) { return this._Testability_15; }
    if ((token === import14.ApplicationRef_)) { return this._ApplicationRef__16; }
    if ((token === import14.ApplicationRef)) { return this._ApplicationRef_17; }
    if ((token === import15.Compiler)) { return this._Compiler_18; }
    if ((token === import53.APP_ID)) { return this._APP_ID_19; }
    if ((token === import74.DOCUMENT)) { return this._DOCUMENT_20; }
    if ((token === import16.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_21; }
    if ((token === import17.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_22; }
    if ((token === import17.EventManager)) { return this._EventManager_23; }
    if ((token === import18.DomSharedStylesHost)) { return this._DomSharedStylesHost_24; }
    if ((token === import75.AnimationDriver)) { return this._AnimationDriver_25; }
    if ((token === import19.DomRootRenderer)) { return this._DomRootRenderer_26; }
    if ((token === import14.NgProbeToken)) { return this._NgProbeToken_27; }
    if ((token === import76.RootRenderer)) { return this._RootRenderer_28; }
    if ((token === import20.DomSanitizer)) { return this._DomSanitizer_29; }
    if ((token === import77.Sanitizer)) { return this._Sanitizer_30; }
    if ((token === import21.AnimationQueue)) { return this._AnimationQueue_31; }
    if ((token === import22.ViewUtils)) { return this._ViewUtils_32; }
    if ((token === import78.IterableDiffers)) { return this._IterableDiffers_33; }
    if ((token === import79.KeyValueDiffers)) { return this._KeyValueDiffers_34; }
    if ((token === import18.SharedStylesHost)) { return this._SharedStylesHost_35; }
    if ((token === import23.Title)) { return this._Title_36; }
    if ((token === import24.RadioControlRegistry)) { return this._RadioControlRegistry_37; }
    if ((token === import25.BrowserXhr)) { return this._BrowserXhr_38; }
    if ((token === import26.ResponseOptions)) { return this._ResponseOptions_39; }
    if ((token === import80.XSRFStrategy)) { return this._XSRFStrategy_40; }
    if ((token === import27.XHRBackend)) { return this._XHRBackend_41; }
    if ((token === import28.RequestOptions)) { return this._RequestOptions_42; }
    if ((token === import81.Http)) { return this._Http_43; }
    if ((token === import29.RestDataSource)) { return this._RestDataSource_44; }
    if ((token === import30.ProductRepository)) { return this._ProductRepository_45; }
    if ((token === import31.StaticDataSource)) { return this._StaticDataSource_46; }
    if ((token === import32.Cart)) { return this._Cart_47; }
    if ((token === import33.Order)) { return this._Order_48; }
    if ((token === import34.OrderRepository)) { return this._OrderRepository_49; }
    if ((token === import35.AuthService)) { return this._AuthService_50; }
    if ((token === import9.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_51; }
    if ((token === import59.LocationStrategy)) { return this._LocationStrategy_52; }
    if ((token === import36.Location)) { return this._Location_53; }
    if ((token === import37.UrlSerializer)) { return this._UrlSerializer_54; }
    if ((token === import38.RouterOutletMap)) { return this._RouterOutletMap_55; }
    if ((token === import82.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_56; }
    if ((token === import83.ROUTES)) { return this._ROUTES_57; }
    if ((token === import71.Router)) { return this._Router_58; }
    if ((token === import84.ActivatedRoute)) { return this._ActivatedRoute_59; }
    if ((token === import40.NoPreloading)) { return this._NoPreloading_60; }
    if ((token === import40.PreloadingStrategy)) { return this._PreloadingStrategy_61; }
    if ((token === import40.RouterPreloader)) { return this._RouterPreloader_62; }
    if ((token === import40.PreloadAllModules)) { return this._PreloadAllModules_63; }
    if ((token === import9.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_64; }
    if ((token === import53.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_65; }
    if ((token === import41.StoreFirstGuard)) { return this._StoreFirstGuard_66; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__16.ngOnDestroy();
    this._DomSharedStylesHost_24.ngOnDestroy();
    this._RouterPreloader_62.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);